CREATE TABLE TB_COLHEITA (
    ID_COLHEITA         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TALHAO           VARCHAR2(20)   NOT NULL,
    AREA_HA             NUMBER(10, 2)  NOT NULL,
    PRODUCAO_ESTIMADA   NUMBER(10, 2)  NOT NULL,
    PRODUCAO_REALIZADA  NUMBER(10, 2)  NOT NULL,
    TIPO_COLHEITA       VARCHAR2(10)   NOT NULL,
    DATA_COLHEITA       DATE           NOT NULL,
    PERCENTUAL_PERDA    NUMBER(5, 2),
    STATUS_PERDA        VARCHAR2(20)
);
